apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
  - name: "http-7001"
    port: 7001
  - name: "http-7000"
    port: 7000
  - name: "http-9042"
    port: 9042
  - name: "http-9160"
    port: 9160
  selector:
    service: cassandra
  clusterIP: None
