apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  ports:
  - name: "7001"
    port: 7001
  - name: "7000"
    port: 7000
  - name: "9042"
    port: 9042
  - name: "9160"
    port: 9160
  selector:
    service: cassandra
  clusterIP: None
