apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: homer
    spec:
      containers:
      - image: "{{ .Values.image.path }}/homer:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: homer
        ports:
        - containerPort: 22
        - containerPort: 7888
        envFrom:
        - configMapRef:
              name: {{ .Values.config.configmaps }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 7888
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 7888
      restartPolicy: Always
