apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ralf
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ralf
  template:
    metadata:
      labels:
        service: ralf
        snmp: enabled
    spec:
      containers:
      - image: "{{ .Values.image.path }}/ralf:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: ralf
        ports:
        - containerPort: 22
        - containerPort: 10888
        envFrom:
        - configMapRef:
              name: {{ .Values.config.configmaps }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 10888
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 10888
        volumeMounts:
        - name: ralflogs
          mountPath: /var/log/ralf
      - image: busybox
        name: tailer
        command: [ "tail", "-F", "/var/log/ralf/ralf_current.txt" ]
        volumeMounts:
        - name: ralflogs
          mountPath: /var/log/ralf
      volumes:
      - name: ralflogs
        emptyDir: {}
      restartPolicy: Always
