---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhcp
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-dhcp-ds
  namespace: kube-system
  labels:
    tier: node
    app: dhcp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: dhcp
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: dhcp
      containers:
      - name: install-dhcp
        image: openretriever/ubuntu-dhcp
        command: [ "/bin/bash", "-c", "service isc-dhcp-server start; while true; do sleep 3600; done" ]
        securityContext:
          privileged: true
