---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhcp
  namespace: kube-system
  annotations:
    container.apparmor.security.beta.kubernetes.io/kube-dhcp: unconfined
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dhcp
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dhcp
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: dhcp
      containers:
      - name: install-dhcp
        image: openretriever/ubuntu-dhcp
        command: [ "/bin/bash", "/usr/local/bin/start.sh" ]
        securityContext:
          privileged: true
