apiVersion: v1
kind: Service
metadata:
  name: bono
spec:
  externalIPs:
  ports:
  - name: "3478"
    port: 3478
    protocol: TCP
    targetPort: 3478
  - name: "5060"
    port: 5060
    protocol: TCP
    targetPort: 5060
  - name: "5062"
    port: 5062
    protocol: TCP
    targetPort: 5062
  selector:
    service: bono
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        networks: '[
          { "name": "calico"},
          { "name": "weave"}
        ]'
    spec:
      containers:
      - name: busybox
        image: bcmt-registry:5000/busybox:latest
        command: ["top"]
        stdin: true
        tty: true
      dnsPolicy: Default

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        networks: '[
          { "name": "calico"},
          { "name": "weave"}
        ]'
    spec:
      containers:
      - name: busybox
        image: bcmt-registry:5000/busybox:latest
        command: ["top"]
        stdin: true
        tty: true
      dnsPolicy: Default

