# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "fuel" do | h |
    h.vm.host_name = "fuel"
    h.vm.provision :shell, :inline => "/vagrant/build_fuel_plugin.sh", privileged: false
    h.vm.synced_folder "..", "/fuel-plugin"
    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
    end
  end
end
