apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.27.2
        command:
          - sleep
          - "36000"
