apiVersion: v1
kind: Service
metadata:
  name: snort-service 
  labels:
    app: snort 
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: snort 
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: snort-pod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: snort
    spec:
      containers:
      - name: snort 
        image: linton/docker-snort 
        ports:
        - containerPort: 80
