VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ceph/ubuntu-xenial"
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 8192
    libvirt.cpus = 4
  end
  
  config.vm.define "ovs-virtio" do | h |
    config.vm.host_name = "ovs-virtio"
    config.vm.provision "shell", path: "setup.sh", privileged: false
  end
end
