sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_cm:2.1.0-SNAPSHOT
sudo docker pull registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/library/cassandra:3.11
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_fs:2.1.0-SNAPSHOT
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_gui:2.1.0-SNAPSHOT
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_hello:2.1.0-SNAPSHOT
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_locate:2.1.0-SNAPSHOT
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_oauth:2.1.0-SNAPSHOT
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aaf/aaf_service:2.1.0-SNAPSHOT
sudo docker pull nexus3.onap.org:10001/onap/aaf/sms:latest
sudo docker pull nexus3.onap.org:10001/onap/aaf/smsquorumclient:latest
sudo docker pull nexus3.onap.org:10001/library/vault:0.10.0
sudo docker pull nexus3.onap.org:10001/library/consul:1.0.6
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull docker.io/aaionap/haproxy:1.2.2
sudo docker pull nexus3.onap.org:10001/onap/babel:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull cassandra:2.1
sudo docker pull cassandra:2.1
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/champ:1.2-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/data-router:1.2-STAGING-latest
sudo docker pull docker.io/elasticsearch:2.4.1
sudo docker pull nexus3.onap.org:10001/onap/gizmo:1.1-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull docker.io/aaionap/hbase:1.2.0
sudo docker pull nexus3.onap.org:10001/onap/model-loader:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aai-resources:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/search-data-service:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/sparky-be:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aai-traversal:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/aai-traversal:1.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/appc-image:1.3.0-SNAPSHOT-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/appc-cdt-image:1.3.0-SNAPSHOT-latest
sudo docker pull registry.hub.docker.com/library/mysql:5.7
sudo docker pull gcr.io/google-samples/xtrabackup:1.0
sudo docker pull registry.hub.docker.com/library/mysql:5.7
sudo docker pull gcr.io/google-samples/xtrabackup:1.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/ccsdk-dgbuilder-image:0.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/policy-pe:1.2.2
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/clamp:2.0-STAGING-latest
sudo docker pull registry.hub.docker.com/library/busybox:latest
sudo docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.9
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull docker.elastic.co/kibana/kibana:5.6.9
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull docker.elastic.co/logstash/logstash:5.6.9
sudo docker pull nexus3.onap.org:10001/mariadb:10.1.11
sudo docker pull nexus3.onap.org:10001/onap/cli:2.0-STAGING-latest
sudo docker pull nexus3.onap.org:10001/oomk8s/consul:1.0.0
sudo docker pull nexus3.onap.org:10001/consul:1.0.6
sudo docker pull registry.hub.docker.com/library/busybox:latest
sudo docker pull crunchydata/crunchy-postgres:centos7-10.3-1.8.2
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/org.onap.dcaegen2.deployments.k8s-bootstrap-container:latest
sudo docker pull nexus3.onap.org:10001/onap/org.onap.dcaegen2.deployments.cm-container:latest
sudo docker pull registry.hub.docker.com/library/busybox:latest
sudo docker pull crunchydata/crunchy-postgres:centos7-10.3-1.8.2
sudo docker pull nexus3.onap.org:10001/onap/org.onap.dcaegen2.deployments.healthcheck-container:latest
sudo docker pull nexus3.onap.org:10001/onap/org.onap.dcaegen2.deployments.redis-cluster-container:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/dmaap/buscontroller:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/policy-drools:1.2.2
sudo docker pull nexus3.onap.org:10001/onap/aai/esr-server:latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/aai/esr-gui:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/oom/kube2msb:latest
sudo docker pull registry.hub.docker.com/library/busybox:latest
sudo docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull docker.elastic.co/kibana/kibana:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull docker.elastic.co/logstash/logstash:5.4.3
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/dmaap/dmaap-mr:1.1.4
sudo docker pull registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/wurstmeister/kafka:1.1.0
sudo docker pull registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
sudo docker pull nexus3.onap.org:10001/wurstmeister/zookeeper:latest
sudo docker pull registry.hub.docker.com/library/consul:0.9.3
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/msb/msb_discovery:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/msb/msb_apigateway:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/msb/msb_apigateway:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/multicloud/framework:1.1.2-STAGING
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/multicloud/openstack-ocata:1.1.2-SNAPSHOT
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/multicloud/vio:1.1.2-STAGING
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/multicloud/openstack-windriver:1.1.2-SNAPSHOT
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/externalapi/nbi:latest
sudo docker pull nexus3.onap.org:10001/mariadb:10.2.14
sudo docker pull registry.hub.docker.com/library/mongo:3
sudo docker pull oomk8s/ubuntu-init:1.0.0
sudo docker pull nexus3.onap.org:10001/sonatype/nexus:2.14.8-01
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-osdf:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-has:latest
sudo docker pull nexus3.onap.org:10001/onap/music/cassandra_music:3.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-has:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-has:latest
sudo docker pull nexus3.onap.org:10001/onap/music/music:latest
sudo docker pull nexus3.onap.org:10001/library/tomcat:8.5
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-has:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/optf-has:latest
sudo docker pull nexus3.onap.org:10001/zookeeper:3.4
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/policy-pe:1.2.2
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/policy-pe:1.2.2
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/mariadb:10.2.14
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/portal-app:v2.2.0
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/music/cassandra_music:3.0.0
sudo docker pull nexus3.onap.org:10001/onap/portal-db:v2.2.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/mariadb-client-init:2.0.0
sudo docker pull oomk8s/mariadb-client-init:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/portal-sdk:v2.2.0
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/portal-wms:v2.2.0
sudo docker pull nexus3.onap.org:10001/zookeeper:3.4
sudo docker pull registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/testsuite:1.2.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-backend:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-backend-init:1.2-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/sdc-cassandra:1.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-cassandra-init:1.2-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/sdc-elasticsearch:1.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-init-elasticsearch:1.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-frontend:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-kibana:1.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-onboard-backend:1.2-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdc-onboard-cassandra-init:1.2-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/sdc/sdc-workflow-designer:1.1.0-SNAPSHOT-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdnc-image:1.3-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdnc-ansible-server-image:1.3-STAGING-latest
sudo docker pull registry.hub.docker.com/library/mysql:5.7
sudo docker pull gcr.io/google-samples/xtrabackup:1.0
sudo docker pull registry.hub.docker.com/library/mysql:5.7
sudo docker pull gcr.io/google-samples/xtrabackup:1.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/ccsdk-dgbuilder-image:0.2-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdnc-dmaap-listener-image:1.3-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/admportal-sdnc-image:1.3-STAGING-latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/sdnc-ueb-listener-image:1.3-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/sniroemulator:latest
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/openecomp/mso:1.2.1
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
sudo docker pull nexus3.onap.org:10001/mariadb:10.1.11
sudo docker pull nexus3.onap.org:10001/onap/usecase-ui:latest
sudo docker pull nexus3.onap.org:10001/onap/usecase-ui/usecase-ui-server:latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/catalog:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/emsdriver:1.1.0-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/gvnfmdriver:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/nfvo/svnfm/huawei:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/jujudriver:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/multivimproxy:1.0.0-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/nfvo/svnfm/nokiav2:1.1.0-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/nfvo/svnfm/nokia:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/nslcm:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/resmanagement:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/vnflcm:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/vnfmgr:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/vnfres:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/onap/vfc/wfengine-mgrservice:latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/wfengine-activiti:latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/ztesdncdriver:1.1.0-STAGING-latest
sudo docker pull nexus3.onap.org:10001/onap/vfc/ztevnfmdriver:1.1.0-STAGING-latest
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/vid:1.2.1
sudo docker pull docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull nexus3.onap.org:10001/library/mariadb:10
sudo docker pull oomk8s/readiness-check:2.0.0
sudo docker pull nexus3.onap.org:10001/onap/vnfsdk/refrepo:1.1.1
sudo docker pull registry.hub.docker.com/library/busybox:latest
sudo docker pull crunchydata/crunchy-postgres:centos7-10.3-1.8.2
