$num_workers=3

Vagrant.require_version ">= 1.8.6"
Vagrant.configure("2") do |config|

  config.vm.box = "ceph/ubuntu-xenial"

  config.vm.define "registry" do |config|
    config.vm.hostname = "registry"
    config.vm.provision "shell", path: "registry_setup.sh", privileged: false
    config.vm.network :private_network, ip: "192.168.0.2"
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
  end

  config.vm.define "master" do |config|
    config.vm.hostname = "master"
    config.vm.provision "shell", path: "host_setup.sh", privileged: false
    config.vm.provision "shell", path: "master_setup.sh", privileged: false
    config.vm.network :private_network, ip: "192.168.0.10"
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
    end
  end

  (1 .. $num_workers).each do |i|
    config.vm.define vm_name = "worker%d" % [i] do |config|
      config.vm.hostname = vm_name
      config.vm.provision "shell", path: "host_setup.sh", privileged: false
      config.vm.provision "shell", path: "worker_setup.sh", privileged: false
      config.vm.network :private_network, ip: "192.168.0.#{i+20}"
      config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 33792
        libvirt.cpus = 16
      end
    end
  end

end
