apiVersion: v1
kind: ReplicationController
metadata:
  name: virtiouser
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: virtiouser
    spec:
      containers:
      - name: virtiouser
        image: openretriever/virtio-user-ping
        volumeMounts:
        - mountPath: /dev/hugepages
          name: hugepage-volume
        - mountPath: /var/run
          name: vhost-volume
        command:
          - /root/setup_virtio_user.sh
      volumes:
      - name: hugepage-volume
        hostPath:
          path: /dev/hugepages
      - name: vhost-volume
        hostPath:
          path: /var/run
      restartPolicy: Always
